// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getSystemInfo: () => __TAURI_INVOKE<SystemInfo>("get_system_info"),
	getSystemStats: () => typedError<SystemStats, string>(__TAURI_INVOKE("get_system_stats")),
	getThemePreference: () => __TAURI_INVOKE<ThemePreference>("get_theme_preference"),
	setThemePreference: (preference: ThemePreference) => __TAURI_INVOKE<void>("set_theme_preference", { preference }),
	openUserDir: () => typedError<null, string>(__TAURI_INVOKE("open_user_dir")),
};

/** Events */
export const events = {
	systemStatsEvent: makeEvent<SystemStatsEvent>("system-stats-event"),
};

/* Types */
export type SystemInfo = {
	osFullname: string,
	osArch: string,
};

export type SystemStats = {
	memTotal: string | null,
	memUsed: string | null,
	memAvailable: string | null,
	sampledAt: string,
};

export type SystemStatsEvent = SystemStats;

export type ThemePreference = "System" | "Dark" | "Light";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

