[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "app"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.4", features = [] }

[dependencies]
nfd = "0.0.4"
serde_json = "1.0.85"
serde = { version = "1.0.144", features = [ "derive" ] }
ts-rs = "6.2.0"

[dependencies.tauri]
version = "1.0.5"
features = []

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
