[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "app"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
ts-rs = "6.1"

  [dependencies.tauri]
  version = "1.0.0-beta.8"
  features = []

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
