/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function getSystemInfo() {
    return invoke()<SystemInfoResponse>("get_system_info")
}

export function initHeartbeat() {
    return invoke()<null>("init_heartbeat")
}

export type SystemInfoResponse = { osFullname: string | null; osVersion: string | null; osArch: string | null; memTotal: string | null; memAvailable: string | null }
