// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemInfo = { osFullname: string | null, osVersion: string | null, osArch: string | null, memTotal: string | null, memAvailable: string | null, };