name: Setup
description: Setup and install dependencies

runs:
  using: composite
  steps:
    - run: corepack enable pnpm
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - run: pnpm install --frozen-lockfile
      shell: bash
