name: Setup
description: Setup and install dependencies

runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@stable
    - uses: pnpm/action-setup@v6
    - uses: actions/setup-node@v6
      with: { cache: "pnpm" }
    - run: pnpm install --frozen-lockfile
      shell: bash
