name: Setup
description: Setup and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: .node-version

    - run: corepack enable pnpm
      shell: bash

    - run: rustup toolchain install stable --profile minimal --no-self-update
      shell: bash

    - run: pnpm install --frozen-lockfile
      shell: bash
