name: Setup
description: Setup and install dependencies

runs:
  using: composite
  steps:
    # https://turbo.build/repo/docs/ci/github-actions
    - uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - run: corepack enable pnpm
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - run: rustup toolchain install stable --profile minimal --no-self-update
      shell: bash

    - if: startsWith(runner.os, 'macos')
      run: |
        rustup target add aarch64-apple-darwin
        rustup target add x86_64-apple-darwin
      shell: bash

    - if: startsWith(runner.os, 'windows')
      run: rustup target add x86_64-pc-windows-msvc
      shell: bash

    - run: pnpm install --frozen-lockfile
      shell: bash
