name: Setup
description: Setup and install dependencies

runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@stable
    - uses: pnpm/setup@v3
      with: { cache: true, require-lockfile: true }
