name: Setup
description: Setup and install dependencies

runs:
  using: composite
  steps:
    - run: rustup toolchain install stable --profile minimal --no-self-update
      shell: bash
    - uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
    - uses: pnpm/action-setup@v4
    - run: pnpm install --frozen-lockfile
      shell: bash
