name: Setup
description: Setup and install dependencies

inputs:
  os:
    description: Operating system

runs:
  using: composite
  steps:
    - run: corepack enable pnpm
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - if: startsWith(inputs.os, 'macos')
      run: |
        rustup target add aarch64-apple-darwin
        rustup target add x86_64-apple-darwin
      shell: bash

    - if: startsWith(inputs.os, 'windows')
      run: rustup target add x86_64-pc-windows-msvc
      shell: bash

    - run: pnpm install --frozen-lockfile
      shell: bash
