packages:
  - apps/*
  - packages/*

savePrefix: ''

minimumReleaseAge: 4320 # 3 days in minutes
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
verifyDepsBeforeRun: prompt

catalog:
  '@tsconfig/node26': 26.0.1
  '@tsconfig/strictest': 2.0.8
  '@types/node': 26.6.4
  neverthrow: 8.2.0
  oxlint: 1.86.0
  oxlint-plugin-eslint: 1.86.0

allowBuilds:
  edgedriver: true
  esbuild: true
  geckodriver: true
  lefthook: true
  nx: true
