packages:
  - apps/*
  - packages/*

savePrefix: ''

minimumReleaseAge: 4320 # 3 days in minutes
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
verifyDepsBeforeRun: prompt

catalog:
  '@tsconfig/node26': 26.0.0
  '@tsconfig/strictest': 2.0.8
  '@types/node': 26.2.0
  neverthrow: 8.2.0
  oxlint: 1.78.0
  oxlint-plugin-eslint: 1.78.0

allowBuilds:
  lefthook: true
  nx: true

minimumReleaseAgeExclude:
  - '@oxlint/*'
  - oxlint
