// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getSystemInfo: () => __TAURI_INVOKE<SystemInfo>("get_system_info"),
	getSystemStats: () => typedError<SystemStats, string>(__TAURI_INVOKE("get_system_stats")),
	getThemePreference: () => __TAURI_INVOKE<ThemePreference>("get_theme_preference"),
	setThemePreference: (preference: ThemePreference) => __TAURI_INVOKE<void>("set_theme_preference", { preference }),
};

/** Events */
export const events = {
	systemStatsEvent: makeEvent<SystemStatsEvent>("system-stats-event"),
};

/* Types */
export type SystemInfo = {
	osFullname: string,
	osArch: string,
};

export type SystemStats = {
	memTotal: string | null,
	memUsed: string | null,
	memAvailable: string | null,
	sampledAt: string,
};

export type SystemStatsEvent = SystemStats;

export type ThemePreference = "System" | "Dark" | "Light";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}
