// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SysInfoResponse { name: string | null, osVersion: string | null, hostName: string | null, }