name: Test and lint
description: Run linters and unit / integration tests

runs:
  using: composite
  steps:
    - run: bun test:ci
      shell: bash

    - run: bun typecheck
      shell: bash

    - run: bun lint
      shell: bash
