name: E2E

on:
  workflow_dispatch:

jobs:
  e2e:
    name: E2E Tests
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: pnpm nx e2e apps/app-e2e
